import localFont from "next/font/local";
import Sidebar from "../components/sidebar";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Testing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-100 flex py-0 lg:py-5 px-0 lg:px-10 gap-5 lg:overflow-hidden relative`}
      >
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
